service: cloudwave-events-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  timeout: 30
  environment:
    MONGO_URI: "mongodb+srv://cloudwave-user:CloudWave2024@cloudwave-cluster.zcijbsp.mongodb.net/cloudwave?appName=cloudwave-cluster"
    BUCKET_NAME: "cloudwave-uploads-bucket"
    SES_EMAIL: "prabathbandara100@gmail.com"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: "*"
        - Effect: Allow
          Action:
            - ses:SendEmail
          Resource: "*"

functions:
  getEvents:
    handler: src/events/getEvents.handler
    events:
      - http:
          path: events
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  createEvent:
    handler: src/events/createEvent.handler
    events:
      - http:
          path: events
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  getEventById:
    handler: src/events/getEventById.handler
    events:
      - http:
          path: events/{id}
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  updateEvent:
    handler: src/events/updateEvent.handler
    events:
      - http:
          path: events/{id}
          method: put
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  deleteEvent:
    handler: src/events/deleteEvent.handler
    events:
      - http:
          path: events/{id}
          method: delete
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  registerEvent:
    handler: src/registrations/registerEvent.handler
    events:
      - http:
          path: registrations
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  getPresignedUrl:
    handler: src/uploads/getPresignedUrl.handler
    events:
      - http:
          path: uploads/presigned-url
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  sendReminders:
    handler: src/reminders/sendReminders.handler
    events:
      - schedule: rate(1 day)