name: Deploy CloudWave Backend

on:
  push:
    branches: [main]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Deploy to AWS
        run: serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ AKIAIOSFODNN7EXAMPLE }}
          AWS_SECRET_ACCESS_KEY: ${{ wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY }}
          AWS_DEFAULT_REGION: ap-southeast-1
          MONGO_URI: ${{ mongodb+srv://cloudwave-user :CloudWave2024@cloudwave-cluster.zcijbsp.mongodb.net/? appName=cloudwave-cluster }}
          BUCKET_NAME: ${{ cloudwave-uploads-bucket }}
          SES_EMAIL: ${{ prabathbandara100@gmail.com }}